### ISSUE TITLE
Port our examples to Rust 2018 edition!

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#1099]
Let's port our examples to the 2018 edition!

## How to port an example crate

1. Leave a comment here claiming an example, so that we don't duplicate work.
2. Run `cargo fix --edition`
3. Add `edition = "2018"` to the `[package]` section of the example's `Cargo.toml`
4. Run `cargo check --target wasm32-unknown-unknown`
    - If it compiles OK and without any warnings:
        - commit your changes and send a PR!
    - Otherwise:
        - trouble shoot, fix any errors and warnings, go back to the start of step 4.
5. (optional) Run `cargo fix --edition-idioms` and remove all `extern crate` directives

The [2018 edition guide](https://rust-lang-nursery.github.io/edition-guide/introduction.html) might be helpful reading.

## TODO

- [x] `examples/add/`
- [x] `examples/canvas/`
- [x] `examples/char/`
- [x] `examples/closures/`
- [x] `examples/console_log/`
- [x] `examples/dom/`
- [x] `examples/duck-typed-interfaces/`
- [x] `examples/fetch/`
- [x] `examples/guide-supported-types-examples/`
- [x] `examples/hello_world/`
- [x] `examples/import_js/`
- [ ] `examples/julia_set/`
- [ ] `examples/no_modules/`
- [ ] `examples/paint/`
- [ ] `examples/performance/`
- [x] `examples/raytrace-parallel/`
- [x] `examples/README.md`
- [x] `examples/todomvc/`
- [x] `examples/wasm2js/`
- [x] `examples/wasm-in-wasm/`
- [x] `examples/webaudio/`
- [x] `examples/webgl/`

**Comment by andrehjr** [comment]
Can I work on add, canvas, char, and hello_world?

Already tried running `cargo fix --edition` on a few examples, and they mostly work without any warnings or issues. So, they only change necessary for those cases is to add `edition = "2018"` on Cargo.toml?

**Comment by elpiel** [comment]
I will pickup the `console_log` as a start.

**Comment by andrehjr** [comment]
Picking up webgl, webaudio, wasm-in-wasm and todomvc

**Comment by T5uku5hi** [comment]
I'll pickup `dom`, `fetch`, `guide-supported-types-examples`, `import_js`.

**Comment by elpiel** [comment]
I will try to implement `julia_set`, `no_modules`, `paint` and `performance`

**Comment by andrehjr** [comment]
Will try raytrace-parallel now!

**Comment by alexcrichton** [comment]
Thanks all for all the assistance!

**Comment by fitzgen** [comment]
Thanks everyone! ^_^

**Comment by elpiel** [comment]
The least I can do and still be useful :blush: Thanks also for your quick responses!
