### ISSUE TITLE
Tracking issue for Parcel compatibility

### ISSUE THREAD

**Issue by mvlabat** [rustwasm/wasm-bindgen#182]
Hi! This is not a bug report (for now I think there isn't any), but just a support request. I wasn't sure it was right to open the issue in this repository, but it seems to me that here I have more chances to get some help. )

I'm trying to get "greet" example (from readme) working with Parcel.

On Rust side everything is compiled successfully. I run `wasm-bindgen target/wasm32-unknown-unknown/debug/js_hello_world.wasm --out-dir .` command and then import the generated js file like this:
```js
import { greet } from "./js_hello_world.js";
```

After that I run parcel to build everything as is. But when opening the page in browser I get the following error in console:
```
Uncaught Error: Cannot find module './js_hello_world_bg'
```

Parcel expects `js_hello_world_bg` file to have `js` extension, but not `wasm`. Modifying `import` statement appending `wasm` to the module path fixes the error, but then I get another one:
```
Uncaught (in promise) TypeError: WebAssembly Instantiation: Imports argument must be present and must be an object
```

I don't know how to fix this one. I would be grateful for any help. Thank you!

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is similar to https://github.com/rustwasm/wasm-bindgen/issues/154 in that parcel [doesn't have enough support](https://github.com/parcel-bundler/parcel/issues/647) for wasm at the moment to get this natively working (unfortunately)

**Comment by alexcrichton** [comment]
Hm although actually I'm gonna leave this open to track parcel support!

**Comment by xtuc** [comment]
FYI https://github.com/parcel-bundler/parcel/issues/1325

**Comment by catsigma** [comment]
I've made a plugin to solve this issue.
https://www.npmjs.com/package/parcel-plugin-wasmbindgen

It works for me.

**Comment by fitzgen** [comment]
@catsigma where is the source located? I don't see a repo link from the npm page

**Comment by catsigma** [comment]
@fitzgen https://github.com/catsigma/parcel-plugin-wasmbindgen

**Comment by fitzgen** [comment]
@catsigma this is a nice start! For us to promote the plugin, I think we would want:

* [ ] documentation describing what this is, how to use it, etc
* [ ] use `wasm-pack` instead of implementing its orchestration of `cargo build --target wasm32-unknown-unknown`, running the `wasm-bindgen` CLI, and all that. See https://github.com/wasm-tool/wasm-pack-plugin for example (webpack version).
* [ ] Eventually, something like https://github.com/rustwasm/rust-webpack-template

**Comment by catsigma** [comment]
@fitzgen thanks, I'll mod the plugin according to your tips.

**Comment by catsigma** [comment]
@sendilkumarn 
yes, I'd love to. 
I'm going to let it support both `wasm-pack` and `cargo & wasm-bindgen`(if wasm-pack is missing).

**Comment by sendilkumarn** [comment]
@catsigma a great work, thanks  👍

**Comment by sendilkumarn** [comment]
@catsigma check [this](https://github.com/sendilkumarn/rust-parcel-template) out.

@fitzgen will transfer the repo once the repo is created.

**Comment by catsigma** [comment]
@sendilkumarn 
Great! Thank you for telling me.




Sunday, September 23, 2018, 19:11 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by alexcrichton** [comment]
I'm gonna close this in favor of https://github.com/rustwasm/rust-parcel-template now, new issues should go there!

**Comment by 0xcaff** [comment]
This issue should be re-opened as parcel doesn't work with the generated stub and the way rust-parcel-template works doesn't allow for using the typescript typings.

**Comment by mvlabat** [comment]
@0xcaff hello! What problem do you have exactly? And could you clarify what do you mean by "doesn't allow for using the typescript typing"? I didn't work with typescript, but my JS project work great at the moment.

Would be glad to help!

**Comment by 0xcaff** [comment]
Hey @mvlabat !

When using rust-parcel-template, with an import like the following:

    import module from '../crate/Cargo.toml'

typescript doesn't know the type of `module`. It compiles just fine because parcel's typescript compilation doesn't seem to fail on type errors, but all of the tooling reports errors (`tsc --noEmit`, IDEs) about the type not being known.

Usually, you can tell typescript to use certain types for a module with ambient module declarations, but ambient module declarations [don't seem to work with relative paths](https://stackoverflow.com/questions/45785620/relative-import-cannot-resolve-to-an-ambient-module).

wasm-bindgen already generates the typings, but typescript needs to be told about them outside of the build step so development tools work.

The way that probably fits this use case best is building with `wasm-pack` and publishing to NPM, but the imported NPM module doesn't work with parcel (even with `parcel-plugin-wasm.rs`).

**Comment by skyne98** [comment]
@0xcaff, for now there is a work-around I found. 

* Create an index.d.ts file where your index.ts (or index.js) is
* Add following to it
```typescript
declare module "*.toml" {
    const value: typeof import('../crate/pkg/rust_parcel_bg');
    export default value;
}
```
* Change `../crate/pkg/rust_parcel_bg` to fit your folder structure and file names
* Profit, you now have types!

**Comment by sliminality** [comment]
@skyne98, what do you mean by this?

> Change `../crate/pkg/rust_parcel` to fit your folder structure and file names

I'm having the same problem, hoping to resolve!

**Comment by chinoto** [comment]
I've found a partial* fix for this: `ln -s pkg/{package_name}.d.ts Cargo.toml.d.ts`. The next time you run parcel, the typing file in pkg will be created and the symbolic link will make your import of Cargo.toml properly typed.
*You don't get typings for `{package_name}_bg.wasm.d.ts`, not sure how to get around this, though it shouldn't usually matter.
